# Generated by Django 3.0.8 on 2020-09-12 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localization', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterModel',
            fields=[
                ('models_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Models')),
            ],
            options={
                'verbose_name': 'Модель принтера',
                'verbose_name_plural': 'Модели принтеров',
            },
            bases=('main.models',),
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.CharField(max_length=40, unique=True, verbose_name='Серийный номер')),
                ('date', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Category', verbose_name='Категория оборудования')),
                ('modelProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Models', verbose_name='Модель')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localization.Room', verbose_name='Локация')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Status', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтеры',
            },
        ),
    ]
