# Generated by Django 3.1.1 on 2020-10-12 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localization', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Фирма')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Фирма принтера',
                'verbose_name_plural': 'Фирмы принтеров',
            },
        ),
        migrations.CreateModel(
            name='PrinterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название модели принтера')),
                ('photo', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Модель принтера',
                'verbose_name_plural': 'Модели принтеров',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус принтера',
                'verbose_name_plural': 'Статусы принтеров',
            },
        ),
        migrations.CreateModel(
            name='PtinterCatrige',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер')),
                ('printerModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printer.printermodel', verbose_name='Модель принтера')),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.CharField(max_length=40, unique=True, verbose_name='Серийный номер')),
                ('ip', models.CharField(blank=True, max_length=30, verbose_name='IP-адрес')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория оборудования')),
                ('printerModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printer.printermodel', verbose_name='Модель принтера')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localization.room', verbose_name='Локация')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printer.status', verbose_name='Статус принтера')),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтеры',
            },
        ),
        migrations.CreateModel(
            name='ModelFirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(auto_created=True, unique=True, verbose_name='Номер')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printer.firm', verbose_name='Фирма')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printer.printermodel', verbose_name='Модель принтера')),
            ],
        ),
    ]
