# Generated by Django 3.0.8 on 2020-09-13 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0003_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус принтера', 'verbose_name_plural': 'Статусы принтеров'},
        ),
        migrations.AddField(
            model_name='printer',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='printer.Status', verbose_name='Статус принтера'),
            preserve_default=False,
        ),
    ]
