# Generated by Django 3.0.8 on 2020-09-15 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0004_auto_20200913_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printer',
            name='date',
        ),
    ]
