# Generated by Django 3.0.8 on 2020-09-12 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Цвет')),
                ('word', models.CharField(max_length=1, unique=True, verbose_name='Обозначение')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='CatrigeModel',
            fields=[
                ('models_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Models')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catrige.Color', verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Модель картриджа',
                'verbose_name_plural': 'Модели картриджей',
            },
            bases=('main.models',),
        ),
        migrations.CreateModel(
            name='Catriege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.CharField(max_length=40, unique=True, verbose_name='Серийный номер')),
                ('date', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Category', verbose_name='Категория оборудования')),
                ('modelProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Models', verbose_name='Модель')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Status', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Картридж',
                'verbose_name_plural': 'Картриджи',
            },
        ),
    ]
