# Generated by Django 3.0.8 on 2020-09-13 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0004_auto_20200913_1007'),
        ('catrige', '0002_remove_catriege_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterCatrigeCompatibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catrige.CatrigeModel', verbose_name='Модель картриджа')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printer.PrinterModel', verbose_name='Модель принтера')),
            ],
            options={
                'verbose_name': 'Картридж',
                'verbose_name_plural': 'Картриджи',
            },
        ),
    ]
