# Generated by Django 3.0.8 on 2020-09-15 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catrige', '0003_printercatrigecompatibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус картриджа',
                'verbose_name_plural': 'Статусы картриджей',
            },
        ),
        migrations.AlterModelOptions(
            name='printercatrigecompatibility',
            options={'verbose_name': 'Совместимость картриджа', 'verbose_name_plural': 'Совместимость картриджей'},
        ),
        migrations.AddField(
            model_name='catriege',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catrige.Status', verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
